<?php
/**
 * @file
 * Change some fields on payment_node_form.
 */


/**
 * Implements hook_form_payment_node_form_alter()
*/
function payment_form_form_payment_node_form_alter(&$form, $form_state, $form_id) {
  
  $form_state['group_hidden'] = array(
    '#type' => 'hidden',
  );
}

function  payment_form_form_alter(&$form, $form_state, $form_id) {
  drupal_set_message('ID формы: '.$form_id);
  $form['group_hidden'] = array(
    '#type' => 'hidden',
  );
}